# Generated by Django 5.0.6 on 2024-05-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.SmallIntegerField(default=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='bicycle', max_length=50, null=True)),
                ('price', models.PositiveIntegerField(default=3500, null=True)),
                ('color', models.TextField(default='black', max_length=50, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_api_practice_app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_month', models.PositiveIntegerField(default=4)),
                ('date_day', models.PositiveIntegerField(default=12)),
                ('date_year', models.PositiveIntegerField(default=2024)),
                ('order_quantity', models.PositiveIntegerField(default=1)),
                ('paid', models.TextField(default='not paid', null=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_api_practice_app.customer')),
                ('vehicles', models.ManyToManyField(related_name='order', to='django_api_practice_app.vehicle')),
            ],
        ),
    ]
