# Generated by Django 5.0.6 on 2024-05-21 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api_practice_app', '0002_alter_customerorder_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='vehicles',
        ),
        migrations.CreateModel(
            name='VehicleInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_specific_ordered_vehicle', models.SmallIntegerField(default=1)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='django_api_practice_app.customerorder')),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_ordered', to='django_api_practice_app.vehicle')),
            ],
        ),
    ]
